# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNcfO9VtgV_BEtPuy4jmQ3BPAeTAJusH

# Section 0: Installing Dependents
"""


### FINAL PROJECT ###

# The main function #

######Set up and check GPU########
import tensorflow as tf
# device_name = tf.test.gpu_device_name()
# if device_name != '/device:GPU:0':
#   raise SystemError('GPU device not found')
# print('Found GPU at: {}'.format(device_name))


####Set Up Keras######
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import plot_model
# import graphviz
import numpy
# set the seed for reproducibility
#numpy.random.seed(7)

#######Load Data as DF#######  
dataset = dataset = numpy.loadtxt("poker_data_clean.csv", delimiter=",",skiprows=1)
# SHUFFLE the rows
numpy.random.shuffle(dataset)



